config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post '/sessions' => 'sessions#create'
  delete '/sessions/' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/search' => 'users#search'
  
  #Nested routes new, show, or index

  #'/users'

  #'/users/:id/games'

  #'/genres'

  #'/genres/:id/games'

  resources :users do
    resources :games
  end

  resources :games

  resources :genres do
    resources :games
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    belongs_to :genre

    validates :title, :platform, presence: true

    default_scope { order(:title) }

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :games
    has_many :users, through: :games

    validates :genre_type, presence: true
    validates :genre_type, uniqueness: true

    def self.genre_with_most_games
        self.joins(:games).group('games.id').order('count(games.id) desc limit 1')
    end
end

app/models/user.rb
class User < ApplicationRecord

    has_many :games
    has_many :genres, through: :games
    has_secure_password

    validates :name, :email, :password, presence: true
    validates :email, uniqueness: true

    accepts_nested_attributes_for :games

    default_scope { order(:name) }

    #scope method for session login omniauth
    def self.find_or_create_by_omniauth(auth_hash)
        self.where(:name => auth_hash['info']['name'], :email => auth_hash['info']['email']).first_or_create do |user|
            user.password = SecureRandom.hex(16)
        end
    end

    def self.user_search(u_search)
        self.where("name LIKE ?", "%" + u_search + "%")
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    before_action :redirect_if_not_logged_in
    before_action :find_game #use private method for finding game as a before action call

    def new
        @game = Game.new(user_id: params[current_user.id])
    end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @games = @user.games
        else
            @games = Game.all 
        end
    end

    def show
        @user = User.find_by_id(params[:user_id])
    end

    def create
        @game = current_user.games.build(game_params)

        if @game.save
            redirect_to user_path(current_user)
        else
            render :new
        end
    end

    def update
        if @game.update(game_params)
            redirect_to user_game_path(current_user.id, @game)
        else
            render :edit
        end
    end

    def destroy
        @game.destroy
        redirect_to user_games_path(current_user.id)
    end

    private

    def find_game
        @game = Game.find_by_id(params[:id]) #refactor and DRY up find_by_id into one method
    end

    def game_params
        params.require(:game).permit(:title, :platform, :genre_id, :user_id)
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    before_action :redirect_if_not_logged_in

    def index
        @genres = Genre.genre_with_most_games #scope method for index finding the genre with the most games
    end

    def new
        @genre = Genre.new
    end

    def create
        @genre = Genre.new(genre_params)

        if @genre.save
            redirect_to user_path(current_user)
        else
            render :new
        end
    end

    private

    def genre_params
        params.require(:genre).permit(:genre_type)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end


    def create
        if auth_hash = request.env['omniauth.auth']
            @user = User.find_or_create_by_omniauth(auth_hash)
                session[:user_id] = @user.id
                redirect_to user_path(@user)
        else
            @user = User.find_by(email: params[:email])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                redirect_to login_path
            end
        end
    end

    def destroy
        session.clear
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :verify_authenticity_token

    def index
        @users = User.all 
    end

    def search
        @users = User.user_search(params[:name])
        render :index
    end

    def new
        @user = User.new
        @user.games.build #nested attributes build for new view in user signup
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
    end

    private 

    def user_params
        params.require(:user).permit(:name, :email, :password, games_attributes: [:title, :platform, :user_id, :genre_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
    <%= f.text_field :title, placeholder: true %><br><br>

    <%= f.text_field :platform, placeholder: true %><br><br>

    <%= f.label :genre_type %>
    <%= f.collection_select :genre_id, Genre.all, :id, :genre_type %><br><br>

    <%= f.submit "Submit Game" %>

<% end %>

app/views/games/edit.html.erb
<%= form_tag(@game, { class: "game_form" } ) do %>
    <h1>Edit Game Details</h1>
    <% if @game.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @game.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @game.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
        <%= render 'form' %>
    </div>
<% end %>

app/views/games/index.html.erb
    <div class="game_list">
        <h1><%= @user.name %>'s Game Collection </h1>
            <ul>
                <% @user.games.each do |game| %>
                    <li><%= link_to game.title, user_game_path(@user, game.id) %></li>
                <% end %>
            </ul>
    </div>

    <div class="go_back_link">
        <%= link_to "go back", @user %>
    </div>

app/views/games/new.html.erb
<%= form_tag(@game, { class: "game_form" } ) do %>
    <h1>Add a game to your collection</h1>
    <% if @game.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @game.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @game.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
        <%= render 'form' %>
    </div>
<% end %>

app/views/games/show.html.erb
<div class="game_details">
    <h1><%= @user.name %>'s Game Collection Details </h1>
    <p><h3>Title: <%= @game.title %></h3></p>
    <p><h4>Platform: <%= @game.platform %></h4></p>
    <p><h4>Genre type: <%= @game.genre.genre_type %></h4></p>
</div>

<% if @user == current_user %>
<div class="links">
    <%= link_to "edit game details", edit_user_game_path(current_user.id, @game) %> |
    <%= link_to "delete game", @game, method: :delete, data: { confirm: "Are you sure you want to delete this game?" } %><br><br>
</div>
<% end %>

<div class="go_back_link">
    <%= link_to "go back", user_games_path(@user) %>
</div>

app/views/genres/index.html.erb
<div class="genre_most_games">
    <% @genres.each do |genre| %>
        <h1><%= genre.genre_type %></h1>
    <% end %>
</div>


<div class="go_back_link">
    <%= link_to "go back", user_path(current_user.id) %>
</div>

app/views/genres/new.html.erb
<%= form_tag(@genre, { class: "genre_form" } ) do %>
    <h1>Add a Genre</h1>
    <% if @genre.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @genre.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @genre.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
            <%= form_for(@genre) do |f| %>
                <%= f.text_field :genre_type, placeholder: true %>
                <%= f.submit "Add Genre" %><br><br>
            <% end %>
        </div>
<% end %>

<div class="go_back_link">
    <%= link_to "go back", user_path(current_user.id) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videogame Collection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles' %>

  </head>

  <body>

  <div class="nav-bar">
  Video Game Collection |
  <% if logged_in? %>
    <%= link_to 'account', user_path(current_user.id) %> |
    <%= link_to 'logout', sessions_path, method: :delete, data: { confirm: "Are you sure you want to logout?" } %><br>
  <% else %>
    <%= link_to 'signup', '/signup' %>
  <% end %>
  </div>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="user_list">
    <h1>List of Users</h1>

    <h4>Click on a name to view their list of games!</h4>
    <ul>
        <% @users.each do |user| %>
            <li><%= link_to user.name, user_games_path(user.id) %></li><br>
        <% end %>
    </ul>
</div>

<%= form_tag('/search', method: 'get') do %>
    <%= label_tag 'name' %>
    <%= text_field_tag 'name' %>
    <%= submit_tag 'Submit' %>

<% end %>

app/views/users/new.html.erb
<%= form_tag(@user, { class: "signup_form" } )do %>
<h2>Sign Up Here!</h2>
    <% if @user.errors.any? %>
        <div id="error_message">
            <h4>The following errors have occurred:</h4>
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @user.errors.empty? %>
        <div class="field">
    <% else %>
        <div class="field_with_errors">
    <% end %>
        <%= form_for @user, url:'/signup' do |f| %>

            <%= f.text_field :name, placeholder: true %><br><br>

            <%= f.email_field :email, placeholder: true %><br><br>

            <%= f.password_field :password, placeholder: true %><br><br>

            <p>Immediately add a game to your collection at signup!</p>

            <%= f.fields_for :games do |game| %>
                
                <%= game.text_field :title, placeholder: true, required: true %><br><br>

                <%= game.text_field :platform, placeholder: true, required: true %><br><br>

                <%= game.label :genre_type %>
                <%= game.collection_select :genre_id, Genre.all, :id, :genre_type %><br><br>

            <% end %>

            <%= f.submit "Sign Up" %>    
        <% end %>
    </div>        
<% end %>

app/views/users/show.html.erb
<div class="welcome">
    <h1>Welcome <%= current_user.name %>!</h1>
</div>


<div class="links">
    <p>
        <%= link_to 'Add a Game to Your Collection', new_user_game_path(@user) %> |
        <%= link_to 'Add a Genre', new_genre_path %> |
        <%= link_to 'See List of Users', users_path %> |
        <%= link_to 'See your game collection', user_games_path(current_user) %> |
        <%= link_to 'Genre with the Most Games', genres_path %> |
        <%= link_to 'log Out', sessions_path, method: :delete, data: { confirm: "Are you sure you want to logout?" } %><br>
    </p>
</div>